server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: hsp
    url: jdbc:mysql://localhost:3306/ptumall?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8

mybatis:
  mapper-locations: classpath:/mapper/*
jwt:
  SING: "ptu202180" #密钥
  expireTime: 30 #token有效时间 (分钟)

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countsql

file:
  save-path: "D:/Program/java/ptumall/src/main/resources/static/img/"
image:
  prefix-url: "http://127.0.0.1:8080"

swagger:
  enabled: true
